package com.menards.service.design;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-04-10T16:29:42.629-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "DesignService", 
                  wsdlLocation = "file:/Users/marcrisney/Projects/menards/menards-wsdl2rest/wsdl/MenardsDesignService.wsdl",
                  targetNamespace = "http://design.service.menards.com") 
public class DesignService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://design.service.menards.com", "DesignService");
    public final static QName DesignServiceSoapPort = new QName("http://design.service.menards.com", "DesignServiceSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/marcrisney/Projects/menards/menards-wsdl2rest/wsdl/MenardsDesignService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DesignService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/marcrisney/Projects/menards/menards-wsdl2rest/wsdl/MenardsDesignService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DesignService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DesignService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DesignService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DesignService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DesignService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DesignService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DesignService
     */
    @WebEndpoint(name = "DesignServiceSoapPort")
    public DesignService getDesignServiceSoapPort() {
        return super.getPort(DesignServiceSoapPort, DesignService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DesignService
     */
    @WebEndpoint(name = "DesignServiceSoapPort")
    public DesignService getDesignServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(DesignServiceSoapPort, DesignService.class, features);
    }

}
