package com.menards.service.design;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-04-10T16:29:42.575-07:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://design.service.menards.com", name = "DesignService")
@XmlSeeAlso({ObjectFactory.class})
public interface DesignService {

    @WebMethod
    @RequestWrapper(localName = "getPreConfiguredDesignByProgramDesignId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramDesignId")
    @ResponseWrapper(localName = "getPreConfiguredDesignByProgramDesignIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramDesignIdResponse")
    @WebResult(name = "preconfiguredDesignList", targetNamespace = "")
    public com.menards.service.design.PreconfiguredDesignList getPreConfiguredDesignByProgramDesignId(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "designId", targetNamespace = "")
        java.lang.Long designId
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignBlobByDesignId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignBlobByDesignId")
    @ResponseWrapper(localName = "getDesignBlobByDesignIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignBlobByDesignIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignBlob getDesignBlobByDesignId(
        @WebParam(name = "designId", targetNamespace = "")
        java.lang.Long designId
    );

    @WebMethod
    @RequestWrapper(localName = "getAlive", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetAlive")
    @ResponseWrapper(localName = "getAliveResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetAliveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean getAlive();

    @WebMethod
    @RequestWrapper(localName = "setDesign", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetDesign")
    @ResponseWrapper(localName = "setDesignResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetDesignResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignStatus setDesign(
        @WebParam(name = "sendToEstimateFollowUpSystem", targetNamespace = "")
        boolean sendToEstimateFollowUpSystem,
        @WebParam(name = "designAssembly", targetNamespace = "")
        com.menards.service.design.DesignAssembly designAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "setPreConfiguredDesign", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesign")
    @ResponseWrapper(localName = "setPreConfiguredDesignResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesignResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignStatus setPreConfiguredDesign(
        @WebParam(name = "preConfiguredDesignAssembly", targetNamespace = "")
        com.menards.service.design.PreConfiguredDesignAssembly preConfiguredDesignAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "setPreConfiguredDesignActiveFlag", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesignActiveFlag")
    @ResponseWrapper(localName = "setPreConfiguredDesignActiveFlagResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesignActiveFlagResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignActiveStatus setPreConfiguredDesignActiveFlag(
        @WebParam(name = "designActiveAssembly", targetNamespace = "")
        com.menards.service.design.DesignActiveAssembly designActiveAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "setPreConfiguredDesignDeletedFlag", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesignDeletedFlag")
    @ResponseWrapper(localName = "setPreConfiguredDesignDeletedFlagResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetPreConfiguredDesignDeletedFlagResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignDeletedStatus setPreConfiguredDesignDeletedFlag(
        @WebParam(name = "designDeletedAssembly", targetNamespace = "")
        com.menards.service.design.DesignDeletedAssembly designDeletedAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByGuestAccountId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByGuestAccountId")
    @ResponseWrapper(localName = "getDesignByGuestAccountIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByGuestAccountIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByGuestAccountId(
        @WebParam(name = "guestAccountId", targetNamespace = "")
        java.lang.Long guestAccountId
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramSocStore", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramSocStore")
    @ResponseWrapper(localName = "getDesignByProgramSocStoreResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramSocStoreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramSocStore(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "socNumber", targetNamespace = "")
        java.lang.Long socNumber,
        @WebParam(name = "storeNumber", targetNamespace = "")
        java.lang.Integer storeNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramEstimateStore", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramEstimateStore")
    @ResponseWrapper(localName = "getDesignByProgramEstimateStoreResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramEstimateStoreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramEstimateStore(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "estimateNumber", targetNamespace = "")
        java.lang.Long estimateNumber,
        @WebParam(name = "storeNumber", targetNamespace = "")
        java.lang.Integer storeNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getPreConfiguredDesignByProgramAttributeActive", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttributeActive")
    @ResponseWrapper(localName = "getPreConfiguredDesignByProgramAttributeActiveResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttributeActiveResponse")
    @WebResult(name = "preconfiguredDesignList", targetNamespace = "")
    public com.menards.service.design.PreconfiguredDesignList getPreConfiguredDesignByProgramAttributeActive(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "designActive", targetNamespace = "")
        boolean designActive,
        @WebParam(name = "designAttributeList", targetNamespace = "")
        com.menards.service.design.DesignAttributeList designAttributeList
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramSoc", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramSoc")
    @ResponseWrapper(localName = "getDesignByProgramSocResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramSocResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramSoc(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "socNumber", targetNamespace = "")
        java.lang.Long socNumber
    );

    @WebMethod
    @RequestWrapper(localName = "deletePreConfiguredDesignAttribute", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.DeletePreConfiguredDesignAttribute")
    @ResponseWrapper(localName = "deletePreConfiguredDesignAttributeResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.DeletePreConfiguredDesignAttributeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DeleteAttributeStatus deletePreConfiguredDesignAttribute(
        @WebParam(name = "deleteAttributeList", targetNamespace = "")
        com.menards.service.design.DeleteAttributeList deleteAttributeList
    );

    @WebMethod
    @RequestWrapper(localName = "setDesignDeletedFlag", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetDesignDeletedFlag")
    @ResponseWrapper(localName = "setDesignDeletedFlagResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetDesignDeletedFlagResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignDeletedStatus setDesignDeletedFlag(
        @WebParam(name = "designDeletedAssembly", targetNamespace = "")
        com.menards.service.design.DesignDeletedAssembly designDeletedAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByDesignId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByDesignId")
    @ResponseWrapper(localName = "getDesignByDesignIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByDesignIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByDesignId(
        @WebParam(name = "designId", targetNamespace = "")
        java.lang.Long designId
    );

    @WebMethod
    @RequestWrapper(localName = "setGuestAccountDesignAssociation", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetGuestAccountDesignAssociation")
    @ResponseWrapper(localName = "setGuestAccountDesignAssociationResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetGuestAccountDesignAssociationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.AccountDesignAssociationStatus setGuestAccountDesignAssociation(
        @WebParam(name = "accountDesignAssociation", targetNamespace = "")
        com.menards.service.design.AccountDesignAssociation accountDesignAssociation
    );

    @WebMethod
    @RequestWrapper(localName = "getPreConfiguredDesignByProgramAttributeDeleted", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttributeDeleted")
    @ResponseWrapper(localName = "getPreConfiguredDesignByProgramAttributeDeletedResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttributeDeletedResponse")
    @WebResult(name = "preconfiguredDesignList", targetNamespace = "")
    public com.menards.service.design.PreconfiguredDesignList getPreConfiguredDesignByProgramAttributeDeleted(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "designDeleted", targetNamespace = "")
        boolean designDeleted,
        @WebParam(name = "designAttributeList", targetNamespace = "")
        com.menards.service.design.DesignAttributeList designAttributeList
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramEstimate", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramEstimate")
    @ResponseWrapper(localName = "getDesignByProgramEstimateResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramEstimateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramEstimate(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "estimateNumber", targetNamespace = "")
        java.lang.Long estimateNumber
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramDesignId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramDesignId")
    @ResponseWrapper(localName = "getDesignByProgramDesignIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramDesignIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramDesignId(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "designId", targetNamespace = "")
        java.lang.Long designId
    );

    @WebMethod
    @RequestWrapper(localName = "getDesignByProgramGuestAccountId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramGuestAccountId")
    @ResponseWrapper(localName = "getDesignByProgramGuestAccountIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetDesignByProgramGuestAccountIdResponse")
    @WebResult(name = "designList", targetNamespace = "")
    public com.menards.service.design.DesignList getDesignByProgramGuestAccountId(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "guestAccountId", targetNamespace = "")
        java.lang.Long guestAccountId
    );

    @WebMethod
    @RequestWrapper(localName = "getNextDesignId", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetNextDesignId")
    @ResponseWrapper(localName = "getNextDesignIdResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetNextDesignIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.DesignId getNextDesignId(
        @WebParam(name = "storeNumber", targetNamespace = "")
        int storeNumber
    );

    @WebMethod
    @RequestWrapper(localName = "setFollowUpClosedFlag", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetFollowUpClosedFlag")
    @ResponseWrapper(localName = "setFollowUpClosedFlagResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.SetFollowUpClosedFlagResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.menards.service.design.FollowUpClosedStatus setFollowUpClosedFlag(
        @WebParam(name = "followUpClosedAssembly", targetNamespace = "")
        com.menards.service.design.FollowUpClosedAssembly followUpClosedAssembly
    );

    @WebMethod
    @RequestWrapper(localName = "getPreConfiguredDesignByProgramAttribute", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttribute")
    @ResponseWrapper(localName = "getPreConfiguredDesignByProgramAttributeResponse", targetNamespace = "http://design.service.menards.com", className = "com.menards.service.design.GetPreConfiguredDesignByProgramAttributeResponse")
    @WebResult(name = "preconfiguredDesignList", targetNamespace = "")
    public com.menards.service.design.PreconfiguredDesignList getPreConfiguredDesignByProgramAttribute(
        @WebParam(name = "programId", targetNamespace = "")
        java.lang.Integer programId,
        @WebParam(name = "designActive", targetNamespace = "")
        boolean designActive,
        @WebParam(name = "designDeleted", targetNamespace = "")
        boolean designDeleted,
        @WebParam(name = "designAttributeList", targetNamespace = "")
        com.menards.service.design.DesignAttributeList designAttributeList
    );
}
